steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/ai-toolkit-complete:latest'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'gcr.io/$PROJECT_ID/ai-toolkit-complete:latest'
  - 'renenijman/ai-toolkit-complete:latest'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'echo $$DOCKERHUB_TOKEN | docker login --username $$DOCKERHUB_USERNAME --password-stdin'
  secretEnv: ['DOCKERHUB_TOKEN', 'DOCKERHUB_USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'renenijman/ai-toolkit-complete:latest'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/dockerhub-token/versions/latest
    env: 'DOCKERHUB_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/dockerhub-username/versions/latest
    env: 'DOCKERHUB_USERNAME'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  logging: 'CLOUD_LOGGING_ONLY'
