steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/ai-toolkit-complete:latest'
  - '.'
  timeout: '10800s'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/ai-toolkit-complete:latest'
  timeout: '1800s'
options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: '300'
  logging: 'CLOUD_LOGGING_ONLY'
timeout: '12600s'
