steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/ai-toolkit-complete:latest'
  - '.'
  timeout: '10800s'  # 3 hours for the build step (model downloads take time)
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'gcr.io/$PROJECT_ID/ai-toolkit-complete:latest'
  - 'renenijman/ai-toolkit-complete:latest'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'echo $$DOCKERHUB_TOKEN | docker login --username $$DOCKERHUB_USERNAME --password-stdin'
  secretEnv: ['DOCKERHUB_TOKEN', 'DOCKERHUB_USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'renenijman/ai-toolkit-complete:latest'
  timeout: '3600s'  # 1 hour for push (large image)
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/dockerhub-token/versions/latest
    env: 'DOCKERHUB_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/dockerhub-username/versions/latest
    env: 'DOCKERHUB_USERNAME'
options:
  machineType: 'E2_HIGHCPU_32'  # Upgraded machine for faster builds
  diskSizeGb: '300'              # Increased disk space for large models
  logging: 'CLOUD_LOGGING_ONLY'
timeout: '14400s'                # 4 hours total timeout (safety margin)